export const Css = {
	CONTAINER_CLASS                   : 'nx-timeline-container',
	MAIN_ROW_CLASS					  : 'nx-timeline-main-row',
	CENTERED_DIV_CLASS                : 'nx-timeline-centered-div', 	
	MAIN_BODY                         : 'nx-timeline-main-body',
	MAIN_COL                          : 'nx-timeline-main-col',
	TIMETICKS_CONTAINER               : 'nx-timeticks-container', 
	TIMETICKS_ROW                     : 'nx-timeticks-row ',
	TIMELINE_FIRST_COL                : 'nx-timeline-first-column',
	TIMELINE_LABELS                   : 'nx-timeline-labels',
	TIMELINE_BAR                   	  : 'nx-timeline-bar',
	TIMELINE_LINK                 	  : 'nx-timeline-link',
	TIMELINE_ELEM_LABELS			  : 'nx-timeline-elem-labels',
	TIMELINE_BASIC_ELEM				  : 'nx-timeline-basic-elem',
	TIMELINE_BASIC_ELEM_ROW_FRAME	  : 'nx-timeline-basic-elem-row',
	TIMELINE_NOW_LINE				  :	'nx-timeline-now-line',
	TIMELINE_TIMETICKS_CONTENT		  : 'nx-timeline-timeticks-content',
	TIMELINE_ELEM_BOTTOM_LABELS		  : 'nx-timeline-bottom-labels',
	TIMELINE_BOTTOM_CONTAINER		  : 'nx-timeline-bottom-container',
	TIMELINE_HEADER_CONTAINER		  : 'nx-timeline-header-container',
}